server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jwt:
    secret: "super-tajny-klucz-zmien-na-swoj-i-three-maj-len-64b"
    accessMinutes: 15
    refreshDays: 7
    cors:
      origins:
        - "http://localhost:4200"